# Generated by Django 5.2.7 on 2025-11-06 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('category', models.CharField(choices=[('Produce', 'Produce'), ('Dairy', 'Dairy'), ('Meat', 'Meat'), ('Bakery', 'Bakery'), ('Pantry', 'Pantry'), ('Frozen', 'Frozen'), ('Beverages', 'Beverages'), ('Snacks', 'Snacks'), ('Other', 'Other')], max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
