# Generated by Django 5.2.7 on 2025-11-16 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('category', models.CharField(choices=[('Produce', 'Produce'), ('Dairy', 'Dairy'), ('Meat', 'Meat'), ('Bakery', 'Bakery'), ('Pantry', 'Pantry'), ('Frozen', 'Frozen'), ('Beverages', 'Beverages'), ('Snacks', 'Snacks'), ('Other', 'Other')], default='Other', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='GroceryItem',
        ),
    ]
