# Generated by Django 5.2.5 on 2025-11-10 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the name of the grocery item', max_length=200)),
                ('complete', models.BooleanField(default=False, help_text='Check if item has been purchased')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='How many items to buy')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the item', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grocery Item',
                'verbose_name_plural': 'Grocery Items',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'title')},
            },
        ),
    ]
