# Generated by Django 5.2.5 on 2025-11-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucky', '0002_alter_task_options_alter_task_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='task',
            name='price',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Produce', 'Produce'), ('Dairy', 'Dairy'), ('Meat', 'Meat'), ('Bakery', 'Bakery'), ('Pantry', 'Pantry'), ('Frozen', 'Frozen'), ('Beverages', 'Beverages'), ('Snacks', 'Snacks'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
