# Generated by Django 5.2.5 on 2025-11-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucky', '0003_remove_task_notes_remove_task_price_task_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
