# Generated by Django 5.2.5 on 2025-11-12 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lucky', '0004_task_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
